### ISSUE TITLE
Video/Image not available to preview

### ISSUE THREAD

**Issue by ramdevcm** [space-voyager-21/space-voyager#56]
**Describe the bug**
The video is not playing on the same page https://space-voyager.vercel.app/apod

**To Reproduce**
1. Go to 'https://space-voyager.vercel.app/apod'
2. Scroll down to the footer

**Expected behavior**
The video should be playing on the same page, rather than navigating to another window

**Screenshots**
![image](https://user-images.githubusercontent.com/68838234/136692852-6b3824d6-a5b3-4375-8cd9-900af1de8d2f.png)

**Comment by ramdevcm** [comment]
This issue is resolved here: [click here](https://github.com/space-voyager-21/space-voyager/pull/54)

**Comment by mohittk** [comment]
> This issue is resolved here: [click here](https://github.com/space-voyager-21/space-voyager/pull/54)

The merge deploy preview failed. Work on it. Not resolved yet, pal.

**Comment by ramdevcm** [comment]
can you pls tell me a reason that caused to fail!!

It works fine on my machine

**Comment by mohittk** [comment]
> can you pls tell me a reason that caused to fail!!
> 
> It works fine on my machine

Yeah just checkout the build logs.
